name: Industrial CI

on:
  push:
    branches: [ jazzy ]
  pull_request:
    branches: [ jazzy ]
  workflow_dispatch:

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
